# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jinguumirai/cplus_project/tank_game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jinguumirai/cplus_project/tank_game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jinguumirai/cplus_project/tank_game/CMakeFiles /home/jinguumirai/cplus_project/tank_game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jinguumirai/cplus_project/tank_game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

Complete.o: Complete.cpp.o
.PHONY : Complete.o

# target to build an object file
Complete.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Complete.cpp.o
.PHONY : Complete.cpp.o

Complete.i: Complete.cpp.i
.PHONY : Complete.i

# target to preprocess a source file
Complete.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Complete.cpp.i
.PHONY : Complete.cpp.i

Complete.s: Complete.cpp.s
.PHONY : Complete.s

# target to generate assembly for a file
Complete.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/Complete.cpp.s
.PHONY : Complete.cpp.s

GameLib3D.o: GameLib3D.cpp.o
.PHONY : GameLib3D.o

# target to build an object file
GameLib3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameLib3D.cpp.o
.PHONY : GameLib3D.cpp.o

GameLib3D.i: GameLib3D.cpp.i
.PHONY : GameLib3D.i

# target to preprocess a source file
GameLib3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameLib3D.cpp.i
.PHONY : GameLib3D.cpp.i

GameLib3D.s: GameLib3D.cpp.s
.PHONY : GameLib3D.s

# target to generate assembly for a file
GameLib3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/GameLib3D.cpp.s
.PHONY : GameLib3D.cpp.s

asset.o: asset.cpp.o
.PHONY : asset.o

# target to build an object file
asset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/asset.cpp.o
.PHONY : asset.cpp.o

asset.i: asset.cpp.i
.PHONY : asset.i

# target to preprocess a source file
asset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/asset.cpp.i
.PHONY : asset.cpp.i

asset.s: asset.cpp.s
.PHONY : asset.s

# target to generate assembly for a file
asset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/asset.cpp.s
.PHONY : asset.cpp.s

base.o: base.cpp.o
.PHONY : base.o

# target to build an object file
base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base.cpp.o
.PHONY : base.cpp.o

base.i: base.cpp.i
.PHONY : base.i

# target to preprocess a source file
base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base.cpp.i
.PHONY : base.cpp.i

base.s: base.cpp.s
.PHONY : base.s

# target to generate assembly for a file
base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/base.cpp.s
.PHONY : base.cpp.s

game.o: game.cpp.o
.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i
.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s
.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game.cpp.s
.PHONY : game.cpp.s

gamecamera.o: gamecamera.cpp.o
.PHONY : gamecamera.o

# target to build an object file
gamecamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gamecamera.cpp.o
.PHONY : gamecamera.cpp.o

gamecamera.i: gamecamera.cpp.i
.PHONY : gamecamera.i

# target to preprocess a source file
gamecamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gamecamera.cpp.i
.PHONY : gamecamera.cpp.i

gamecamera.s: gamecamera.cpp.s
.PHONY : gamecamera.s

# target to generate assembly for a file
gamecamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gamecamera.cpp.s
.PHONY : gamecamera.cpp.s

gameplay.o: gameplay.cpp.o
.PHONY : gameplay.o

# target to build an object file
gameplay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay.cpp.o
.PHONY : gameplay.cpp.o

gameplay.i: gameplay.cpp.i
.PHONY : gameplay.i

# target to preprocess a source file
gameplay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay.cpp.i
.PHONY : gameplay.cpp.i

gameplay.s: gameplay.cpp.s
.PHONY : gameplay.s

# target to generate assembly for a file
gameplay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay.cpp.s
.PHONY : gameplay.cpp.s

gamestatus.o: gamestatus.cpp.o
.PHONY : gamestatus.o

# target to build an object file
gamestatus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gamestatus.cpp.o
.PHONY : gamestatus.cpp.o

gamestatus.i: gamestatus.cpp.i
.PHONY : gamestatus.i

# target to preprocess a source file
gamestatus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gamestatus.cpp.i
.PHONY : gamestatus.cpp.i

gamestatus.s: gamestatus.cpp.s
.PHONY : gamestatus.s

# target to generate assembly for a file
gamestatus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gamestatus.cpp.s
.PHONY : gamestatus.cpp.s

glad.o: glad.c.o
.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i
.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s
.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/glad.c.s
.PHONY : glad.c.s

main_loop.o: main_loop.cpp.o
.PHONY : main_loop.o

# target to build an object file
main_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main_loop.cpp.o
.PHONY : main_loop.cpp.o

main_loop.i: main_loop.cpp.i
.PHONY : main_loop.i

# target to preprocess a source file
main_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main_loop.cpp.i
.PHONY : main_loop.cpp.i

main_loop.s: main_loop.cpp.s
.PHONY : main_loop.s

# target to generate assembly for a file
main_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main_loop.cpp.s
.PHONY : main_loop.cpp.s

main_process.o: main_process.cpp.o
.PHONY : main_process.o

# target to build an object file
main_process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main_process.cpp.o
.PHONY : main_process.cpp.o

main_process.i: main_process.cpp.i
.PHONY : main_process.i

# target to preprocess a source file
main_process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main_process.cpp.i
.PHONY : main_process.cpp.i

main_process.s: main_process.cpp.s
.PHONY : main_process.s

# target to generate assembly for a file
main_process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main_process.cpp.s
.PHONY : main_process.cpp.s

mesh.o: mesh.cpp.o
.PHONY : mesh.o

# target to build an object file
mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/mesh.cpp.o
.PHONY : mesh.cpp.o

mesh.i: mesh.cpp.i
.PHONY : mesh.i

# target to preprocess a source file
mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/mesh.cpp.i
.PHONY : mesh.cpp.i

mesh.s: mesh.cpp.s
.PHONY : mesh.s

# target to generate assembly for a file
mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/mesh.cpp.s
.PHONY : mesh.cpp.s

model.o: model.cpp.o
.PHONY : model.o

# target to build an object file
model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/model.cpp.o
.PHONY : model.cpp.o

model.i: model.cpp.i
.PHONY : model.i

# target to preprocess a source file
model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/model.cpp.i
.PHONY : model.cpp.i

model.s: model.cpp.s
.PHONY : model.s

# target to generate assembly for a file
model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/model.cpp.s
.PHONY : model.cpp.s

pause.o: pause.cpp.o
.PHONY : pause.o

# target to build an object file
pause.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/pause.cpp.o
.PHONY : pause.cpp.o

pause.i: pause.cpp.i
.PHONY : pause.i

# target to preprocess a source file
pause.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/pause.cpp.i
.PHONY : pause.cpp.i

pause.s: pause.cpp.s
.PHONY : pause.s

# target to generate assembly for a file
pause.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/pause.cpp.s
.PHONY : pause.cpp.s

play.o: play.cpp.o
.PHONY : play.o

# target to build an object file
play.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/play.cpp.o
.PHONY : play.cpp.o

play.i: play.cpp.i
.PHONY : play.i

# target to preprocess a source file
play.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/play.cpp.i
.PHONY : play.cpp.i

play.s: play.cpp.s
.PHONY : play.s

# target to generate assembly for a file
play.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/play.cpp.s
.PHONY : play.cpp.s

playstatus.o: playstatus.cpp.o
.PHONY : playstatus.o

# target to build an object file
playstatus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/playstatus.cpp.o
.PHONY : playstatus.cpp.o

playstatus.i: playstatus.cpp.i
.PHONY : playstatus.i

# target to preprocess a source file
playstatus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/playstatus.cpp.i
.PHONY : playstatus.cpp.i

playstatus.s: playstatus.cpp.s
.PHONY : playstatus.s

# target to generate assembly for a file
playstatus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/playstatus.cpp.s
.PHONY : playstatus.cpp.s

shader.o: shader.cpp.o
.PHONY : shader.o

# target to build an object file
shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shader.cpp.o
.PHONY : shader.cpp.o

shader.i: shader.cpp.i
.PHONY : shader.i

# target to preprocess a source file
shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shader.cpp.i
.PHONY : shader.cpp.i

shader.s: shader.cpp.s
.PHONY : shader.s

# target to generate assembly for a file
shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/shader.cpp.s
.PHONY : shader.cpp.s

title.o: title.cpp.o
.PHONY : title.o

# target to build an object file
title.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/title.cpp.o
.PHONY : title.cpp.o

title.i: title.cpp.i
.PHONY : title.i

# target to preprocess a source file
title.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/title.cpp.i
.PHONY : title.cpp.i

title.s: title.cpp.s
.PHONY : title.s

# target to generate assembly for a file
title.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/title.cpp.s
.PHONY : title.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... Complete.o"
	@echo "... Complete.i"
	@echo "... Complete.s"
	@echo "... GameLib3D.o"
	@echo "... GameLib3D.i"
	@echo "... GameLib3D.s"
	@echo "... asset.o"
	@echo "... asset.i"
	@echo "... asset.s"
	@echo "... base.o"
	@echo "... base.i"
	@echo "... base.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... gamecamera.o"
	@echo "... gamecamera.i"
	@echo "... gamecamera.s"
	@echo "... gameplay.o"
	@echo "... gameplay.i"
	@echo "... gameplay.s"
	@echo "... gamestatus.o"
	@echo "... gamestatus.i"
	@echo "... gamestatus.s"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... main_loop.o"
	@echo "... main_loop.i"
	@echo "... main_loop.s"
	@echo "... main_process.o"
	@echo "... main_process.i"
	@echo "... main_process.s"
	@echo "... mesh.o"
	@echo "... mesh.i"
	@echo "... mesh.s"
	@echo "... model.o"
	@echo "... model.i"
	@echo "... model.s"
	@echo "... pause.o"
	@echo "... pause.i"
	@echo "... pause.s"
	@echo "... play.o"
	@echo "... play.i"
	@echo "... play.s"
	@echo "... playstatus.o"
	@echo "... playstatus.i"
	@echo "... playstatus.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
	@echo "... title.o"
	@echo "... title.i"
	@echo "... title.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

